"""induced_shield.py -- physical induced eddy-current shield: standalonereport + plot, now a thin wrapper over shield_common's physics.Prints the per-mode shielding-factor table and plots the ideal (perfect-conductor)
 surface current plus the per-mode shielding factor, for theliterature/design parameters below. The actual physics (multipole momentsx thin-shell L/R response)
 lives once in shield_common.induced_shield_currents()
and shield_common.ideal_surface_K()
 -- see example.py for the full fieldplot using this same model.Run:  python induced_shield.py"""import numpy as npimport matplotlib.pyplot as pltfrom PSXM_coils import PSXMCoilsfrom shield_common import (MU0, ideal_surface_K, induced_shield_currents,                           SIGMA_CU, D_SHIELD, T_PULSE, M_MODES)
A_SHIELD = 27.5e-3    # m, shield radius (PSXM_sim model value)
I_COIL = 1000.0       # A, main-coil peak currentSHIELD_N = 100        # express K as an equivalent per-point currentdef main()
:    coil_currents = np.array([0, I_COIL, I_COIL, 0, -I_COIL, -I_COIL], float)
    tpl = PSXMCoils(currents=np.zeros(6)
, shield=True, shield_n=SHIELD_N,                    shield_radius=A_SHIELD * 1e3)
    I_shield, info = induced_shield_currents(tpl, coil_currents, t_pulse=T_PULSE,                                             sigma=SIGMA_CU, d=D_SHIELD)
    omega = np.pi / T_PULSE    print(f"pulse : I_coil={I_COIL:.0f} A, width {T_PULSE*1e6:.2f} us -> "          f"f~{omega/(2*np.pi)
/1e6:.3f} MHz")
    print(f"copper: sigma={SIGMA_CU:.2e} S/m, skin depth={info['delta']*1e6:.1f} um, "          f"d={D_SHIELD*1e3:.2f} mm -> d_eff={info['d_eff']*1e6:.1f} um")
    print(f"shield: radius a={A_SHIELD*1e3:.1f} mm\n")
    print(f"dominant quadrupole (m=2)
 shielding factor: {info['S2']:.3e}")
    th = np.linspace(0, 2 * np.pi, 361)
    K_ideal = ideal_surface_K(th, A_SHIELD, coil_currents, m_modes=M_MODES)
    seg = 2 * np.pi * A_SHIELD / SHIELD_N    ideal_peak_A = np.max(np.abs(K_ideal)
)
 * seg    induced_peak_A = np.max(np.abs(I_shield)
)
    print(f"\nideal screening current : peak |K|={np.max(np.abs(K_ideal)
)
:8.1f} A/m,  "          f"per-point peak={ideal_peak_A:6.1f} A")
    print(f"induced (real shell)
    : per-point peak={induced_peak_A:6.1f} A")
    print(f"induced / ideal (peak)
  : {induced_peak_A/ideal_peak_A:.3f}")
    print(f"coil current for reference: {I_COIL:.0f} A per leg")
    # per-mode shielding factor 1/|1+iwt|, for the right-hand plot    mm = np.arange(1, M_MODES + 1)
    tau = MU0 * SIGMA_CU * info["d_eff"] * A_SHIELD / (2 * mm)
    Sfac = 1.0 / np.abs(1 + 1j * omega * tau)
    fig, ax = plt.subplots(1, 2, figsize=(12, 5)
)
    ax[0].plot(np.degrees(th)
, K_ideal)
    ax[0].set_xlabel("θ (deg)
")
    ax[0].set_ylabel("surface current K (A/m)
")
    ax[0].set_title("ideal (perfect-conductor)
 shield surface current")
    ax[0].grid(alpha=0.3)
    ax[1].semilogy(mm, Sfac, "o-")
    ax[1].set_xlabel("azimuthal mode m")
    ax[1].set_ylabel("residual field factor 1/|1+iωτ|")
    ax[1].set_title("shielding factor per mode (lower = better)
")
    ax[1].grid(alpha=0.3, which="both")
    fig.tight_layout()
    fig.savefig("figures/induced_shielding_factor.png", dpi=150)
    print("\nsaved figures/induced_shielding_factor.png")

__name__ == "__main__":    main()
